### ISSUE TITLE
Only first parameter is logged

### ISSUE THREAD

**Issue by ulrichb** [Alorel/console-log-html#1]
The `console.log()`-API supports multiple parameters. Example in Firefox Dev-Tools:

![2016-09-19 01_13_49-new tab](https://cloud.githubusercontent.com/assets/388796/18619822/60fcec94-7e06-11e6-8c3b-8f86be42c584.png)

See also https://developer.mozilla.org/en-US/docs/Web/API/Console/log.

**Comment by Alorel** [comment]
Hey.

I know - I never had to use more than one parameter in the past so my mind just skipped it when I wrote this little lib and unfortunately I don't have time to update it due to other commitments. I'm very happy to merge any changes into master if you're willing to change a few lines in the code, though!

**Comment by ulrichb** [comment]
What should we do with the [`onlyConsole`-parameter](https://github.com/Alorel/console-log-html/blob/27d76f950c3ce3def4de984558f35b8c3ac33a33/console-log-html.js#L31)?

* Should we drop it?
* Should we add `console.logOnlyToConsole()/intoOnlyToConsole()/...` functions next to `console.log()/info()/...`? I think this would be OK because all callers, which call `console.log()` with `onlyConsole=true` already have to know about `ConsoleLogHTML` and then it's also OK that they call another function. Further it improves readability in contrast a an unnamed `true`-argument.
* Another possibility is to use a "magic option" like `console.log("a bool:", true, {_logOnlyToConsole: true})`.

I would prefer option 1, and if we really need this feature option 2.

Note that this has to be a breaking change in any case because atm. `console.log("str", true)` is ambiguous.

**Comment by Alorel** [comment]
Option 1 seems much less cluttered, so I would be in favour of using it as well and it's perfectly fine that changes are breaking; we would state this breaking change clearly in the changelog and release it as 2.0.

**Comment by ulrichb** [comment]
So you mean we should not drop it, and instead add `logOnlyToConsole()/intoOnlyToConsole()/...`. Is the name OK for you?

**Comment by Alorel** [comment]
Yes, perfect. And thank you for taking the time to contribute.

**Comment by ulrichb** [comment]
Oh. Another option would be `console.skipHtml.log()/.info()/...`
I'm asking because it's a bit strange to say "OnlyToConsole" on an operation on `console.` ...

**Comment by Alorel** [comment]
This format sounds even better. In the end all that will need to be done is `npm run dist` and all the testing, minification & documentation will be generated.

**Comment by ulrichb** [comment]
OK. Let's see how `console.skipHtml.log()` works out ...

**Comment by ulrichb** [comment]
"skipHtml" to be discussed ...

**Comment by Alorel** [comment]
Resolved as per #2 and #3
